#!/usr/bin/env bash
url="$(xsel -o)"
starttime=$(date +%s)
if title="$(youtube-dl -e $url)" ; then
    notify-send -u critical -t 3000 "Начало загрузки аудио mp3/q3" "$title - $url"
    if  youtube-dl --ignore-errors -f bestaudio --extract-audio --audio-format mp3 --audio-quality 3 --embed-thumbnail --metadata-from-title "%(title)s" --add-metadata -o '~/YouTubeDL/Audio/%(playlist)s/%(title)s-%(upload_date)s.%(ext)s' $url ; then
    endtime=$(date +%s)
        notify-send -u critical -t 3000 "Успешно загружено за $(($endtime - $starttime)) сек." "$title - $url"
    else 
        notify-send -u critical -t 3000 "Ошибка загрузки" "$title - $url"
    fi
else
    notify-send -u critical -t 3000 "Ошибка обработки ссылки" "$url"
fi
